name: qar-analysis
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Python版本
  - python=3.10
  
  # Web框架
  - fastapi=0.104.1
  - uvicorn=0.24.0
  - jinja2=3.1.2
  - aiofiles=23.2.1
  
  # 数据处理核心
  - pandas=2.1.3
  - numpy=1.24.3
  - scipy=1.11.4
  - scikit-learn=1.3.2
  
  # PyTorch CPU版本
  - pytorch::pytorch=2.1.1
  - pytorch::torchvision=0.16.1
  - pytorch::cpuonly
  
  # 数据可视化
  - plotly=5.17.0
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - folium=0.15.0
  
  # 统计和地理处理
  - statsmodels=0.14.1
  - pyproj=3.6.1
  
  # HTTP和网络
  - requests=2.31.0
  - httpx=0.25.2
  
  # 配置管理
  - python-dotenv=1.0.0
  - pydantic=2.5.0
  
  # 系统监控
  - psutil=5.9.6
  
  # 开发工具
  - jupyter=1.0.0
  - black=23.11.0
  - pytest=7.4.3
  
  # 其他工具
  - tqdm=4.66.1
  - python-dateutil=2.8.2
  
  # pip安装的包
  - pip
  - pip:
    - python-multipart==0.0.6
    - pydantic-settings==2.1.0
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - loguru==0.7.2
    - prometheus-client==0.19.0
